FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Update and install curl, then clean up to reduce image size
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy application code
COPY app.py .

# Create a non-root user and switch to it
# RUN useradd --no-log-init --system --create-home streamlit
# USER streamlit

# Permissions to allow container to run on OpenShift
RUN chgrp -R 0 /app && \
    chmod -R g=u /app

# Expose the port that Streamlit will run on
EXPOSE 8501

# Health check to ensure the service is running
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --fail http://localhost:8501/_stcore/health || exit 1

# Run as a non-privileged user
USER 1001

# Default command to run the application
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
